resolver: lts-9.1

nix:
  enable: true
  packages:
    - libcxx
    - icu
    - gcc
    - ncurses
    - pcre
    - zlib

packages:
- ./curryer
- ./curryer-example

extra-deps: []

flags: {}

extra-package-dbs: []
